
export function renderSettingsPageScript(chinese: boolean): string {
  const t = (zh: string, en: string): string => JSON.stringify(chinese ? zh : en)
  return 'const $ = id => document.getElementById(id);'
    + 'let shownNotes="";'
    + 'let marketSaving=false;let marketEpoch=0;'
    + 'function paintMarket(enabled){const button=$("market-toggle");button.disabled=false;'
    + 'button.setAttribute("aria-checked",String(enabled));button.textContent=enabled?'
    + t('已开启', 'On') + ':' + t('已关闭', 'Off') + ';}'
    + '$("market-toggle").onclick=async()=>{const button=$("market-toggle");'
    + 'const wanted=button.getAttribute("aria-checked")!=="true";marketSaving=true;marketEpoch++;button.disabled=true;'
    + 'try{const r=await fetch("desktop/market/"+(wanted?"enable":"disable"),{method:"POST"});const j=await r.json();'
    + 'if(!r.ok)throw new Error(j.error||' + t('保存失败', 'Save failed') + ');paintMarket(j.enabled);'
    + '$("market-note").textContent=j.enabled?'
    + t('已开启，重启客户端后接入安全市场。', 'Enabled. Restart the client to load the safe marketplace.') + ':'
    + t('已关闭并从 profile 中移除，重启客户端后生效。', 'Disabled and removed from the profile. Restart the client to unload it.') + ';'
    + '}catch(e){$("market-note").textContent=' + t('保存失败：', 'Save failed: ') + '+e.message}'
    + 'finally{marketSaving=false;button.disabled=false}};'

    + 'function renderUpdate(u){if(!u)return;'
    + 'const busy=u.phase==="checking"||u.phase==="downloading"||u.phase==="installing";'
    + '$("update-check").disabled=busy;$("update-install").disabled=busy;'
    // A refused install keeps the offer (and the button) on screen, so the
    // error phase counts as an offer too — same rule as the injected card.
    + 'const has=(u.phase==="available"||u.phase==="error")&&u.info;$("update-install").hidden=!has||busy;'
    + '$("update-dismiss").hidden=!has||u.dismissed||busy;'
    + 'let line="";'
    + 'if(u.phase==="checking")line=' + t('正在检查…', 'Checking…') + ';'
    + 'else if(u.phase==="upToDate")line=' + t('已是最新版本', 'Up to date') + ';'
    // Neither current nor offerable: the releases link in this section header
    // is the way forward, so the line explains instead of claiming success.
    + 'else if(u.phase==="unsupportedPlatform")line='
    + t('已有更新版本，但该版本没有发布本平台的安装包', 'A newer version exists, but this release ships no installer for this platform') + ';'
    + 'else if(u.phase==="available"&&u.info)line=' + t('发现 v', 'Found v') + '+u.info.availableVersion;'
    + 'else if(u.phase==="downloading")line=' + t('下载中 ', 'Downloading ') + '+((u.progress&&u.progress.percent)||0)+"%"'
    + '+(u.progress&&u.progress.downloaded?" · "+(u.progress.downloaded/1048576).toFixed(1)'
    + '+(u.progress.total?"/"+(u.progress.total/1048576).toFixed(1):"")+" MB":"");'
    + 'else if(u.phase==="installing")line=' + t('正在启动安装程序', 'Starting the installer') + ';'
    + 'else if(u.phase==="restartRequired")line=' + t('请安装后重新打开', 'Install it, then reopen') + ';'
    // The reason, not the phase, decides: a refusal publishes only a reason.
    + 'const failed=u.phase==="error"||u.error;'
    + 'if(failed)line=' + t('更新失败：', 'Update failed: ') + '+(u.error||' + t('未知错误', 'unknown error') + ');'
    + '$("update-status").textContent=line;$("update-status").hidden=!line;'
    + '$("update-status").classList.toggle("error",!!failed);'
    + 'const bar=$("update-bar");bar.hidden=u.phase!=="downloading";'
    + 'if(!bar.hidden)bar.firstElementChild.style.width=((u.progress&&u.progress.percent)||0)+"%";'
    // notesHtml is rendered in the main process from the release Markdown.
    // Rebuilding it would reset the box's scroll position and drop any
    // selection, and this runs several times a second while downloading.
    + 'const notes=u.notesHtml||"";$("update-notes").hidden=!notes;'
    + 'if(notes!==shownNotes){shownNotes=notes;$("update-notes").innerHTML=notes}}'
    // Named by WHO started the runtime, then which dsh it is. "本地"/"内置" used
    // to overlap: a client-spawned child was labelled 本地 even when it ran the
    // 内置 copy, and a reused instance the user started themselves got neither.
    + 'function sourceLabel(s){'
    + 'if(s.mode==="probe")return ' + t('本机已运行', 'Already running') + ';'
    + 'if(s.mode==="connect")return ' + t('自定义地址', 'Custom address') + ';'
    + 'const v=s.installedDshVersion?" v"+s.installedDshVersion:"";'
    + 'return s.runtimeSource==="installed"?' + t('客户端启动·本机已安装', 'Client-started · installed') + '+v'
    + ':s.runtimeSource==="npx"?' + t('客户端启动·npx 缓存', 'Client-started · npx cache') + '+v'
    + ':s.runtimeSource==="bundled"?' + t('客户端启动·客户端内置', 'Client-started · bundled') + ':' + t('客户端启动', 'Client-started') + ';}'
    + 'async function refresh(){const readEpoch=marketEpoch;try{const s=await(await fetch("desktop/status")).json();'
    + 'const modeLabel=sourceLabel(s);'
    + '$("status").textContent=modeLabel+(s.childPid?" (PID "+s.childPid+")":"")+" → "+(s.targetUrl||' + t('（未就绪）', '(not ready)') + ')+(s.lastError?" · "+s.lastError:"")'
    // Non-blocking: the cache stays in use; re-running npx is how it updates.
    + '+(s.mode==="local"&&s.npxCacheOutdated?' + t(' · npx 缓存低于内置', ' · npx cache is older than the bundled runtime') + '+(s.dshVersion?" v"+s.dshVersion:"")+' + t('，重新运行 npx 可更新', '; re-run npx to update it') + ':"");'
    + '$("versions").textContent=' + t('桌面客户端 v', 'Desktop client v') + '+s.desktopVersion+' + t(' · 内置 dsh ', ' · bundled dsh ') + '+(s.dshVersion??' + t('不可用', 'unavailable') + ')'
    + '+(s.installedDshVersion?' + t(' · 本机 dsh ', ' · installed dsh ') + '+s.installedDshVersion:"");'
    + 'const c=await(await fetch("desktop/settings")).json();$("url").value=c.serverUrl??"";'
    + 'paintRuntimes(c.smartRuntimes);paintMode(s.selectedMode);paintPort(s.localWebPort);'
    + 'if(!marketSaving&&readEpoch===marketEpoch)paintMarket(s.bundledMarketEnabled);'
    + 'paintDataMode(s.dshDataMode,s.dshDataHome,s.dshDataFallbackReason,s.dshDataFallbackPlugins,s.dshDataModeSelectable);'
    + 'renderUpdate(await(await fetch("desktop/update")).json());'
    + '}catch(e){$("status").textContent=' + t('状态不可用', 'Status unavailable') + '}}'
    + '$("save").onclick=async()=>{try{'
    + 'if(!$("url").value.trim()){$("note").textContent=' + t('请先填写地址', 'Enter an address first') + ';return}'
    + 'const r=await fetch("desktop/settings",{method:"POST",headers:{"content-type":"application/json"},'
    + 'body:JSON.stringify({serverUrl:$("url").value.trim()})});const j=await r.json();'
    + '$("note").textContent=j.saved?(j.mode==="smart"?' + t('正在连接（智能模式：该实例停止时自动回落）', 'Connecting (Smart mode: falls back when that instance stops)') + ':' + t('已保存，正在连接…', 'Saved; connecting…') + ')'
    + ':(' + t('保存失败：', 'Save failed: ') + '+(j.error||' + t('未知错误', 'unknown error') + '));'
    + 'if(j.saved)setTimeout(()=>window.close(),900)}catch(e){$("note").textContent=' + t('保存失败：', 'Save failed: ') + '+e.message}};'
    + 'const ALL_RUNTIMES=["probe","installed","npx","bundled"];'
    + 'function paintMode(mode){const custom=mode==="connect";'
    + '$("mode-smart").classList.toggle("primary",!custom);$("mode-custom").classList.toggle("primary",custom);'
    + '$("smart-block").hidden=custom;$("custom-block").hidden=!custom}'
    + '$("mode-smart").onclick=async()=>{paintMode("smart");'
    + 'try{const s=await(await fetch("desktop/status")).json();if(s.selectedMode!=="connect")return;'
    + 'const r=await fetch("desktop/switch",{method:"POST"});const j=await r.json();'
    + 'if(!j.switched){paintMode("connect");$("note").textContent=' + t('切换失败：', 'Switch failed: ') + '+(j.error||' + t('未知错误', 'unknown error') + ');return}'
    + '$("note").textContent=' + t('正在切换到智能模式…', 'Switching to Smart mode…') + ';setTimeout(()=>window.close(),500)}'
    + 'catch(e){paintMode("connect");$("note").textContent=' + t('切换失败：', 'Switch failed: ') + '+e.message}};'
    + '$("mode-custom").onclick=()=>{paintMode("connect");'
    + 'if(!$("url").value){void(async()=>{try{const p=await(await fetch("desktop/probe")).json();'
    + 'if(p.url&&!$("url").value){$("url").value=p.url;$("note").textContent=' + t('检测到本机已有 Web UI，可直接保存并连接。', 'A Web UI is already running on this machine; save to connect to it.') + '}}catch(e){}})()}};'
    + 'function paintRuntimes(ids){const on=new Set(ids&&ids.length?ids:ALL_RUNTIMES);'
    + 'for(const b of document.querySelectorAll("[data-smart-runtime]"))b.classList.toggle("primary",on.has(b.getAttribute("data-smart-runtime")))}'
    + 'async function saveRuntimes(ids){try{const r=await fetch("desktop/smart-runtimes",{method:"POST",headers:{"content-type":"application/json"},'
    + 'body:JSON.stringify({smartRuntimes:ids})});const j=await r.json();'
    + 'if(runtimeQueued)return j;'
    + 'if(j.saved){paintRuntimes(j.smartRuntimes);$("runtime-note").textContent=' + t('已更新智能连接来源', 'Smart connection sources updated') + '}'
    + 'else{$("runtime-note").textContent=' + t('保存失败：', 'Save failed: ') + '+(j.error||' + t('至少保留一种来源', 'Keep at least one source') + ');paintRuntimes(j.smartRuntimes||ALL_RUNTIMES)}'
    + 'return j}catch(e){if(!runtimeQueued)$("runtime-note").textContent=' + t('保存失败：', 'Save failed: ') + '+e.message;return null}}'
    + 'let runtimeBusy=false,runtimeQueued;'
    + 'function commitRuntimes(ids){paintRuntimes(ids);$("runtime-note").textContent=' + t('正在更新智能连接来源…', 'Updating Smart-mode sources…') + ';'
    + 'if(runtimeBusy){runtimeQueued=ids;return}runtimeBusy=true;'
    + 'void saveRuntimes(ids).then(()=>{runtimeBusy=false;if(runtimeQueued){const q=runtimeQueued;runtimeQueued=undefined;commitRuntimes(q)}})}'
    + 'for(const b of document.querySelectorAll("[data-smart-runtime]"))b.onclick=()=>{'
    + 'const id=b.getAttribute("data-smart-runtime");'
    + 'const current=[...document.querySelectorAll("[data-smart-runtime].primary")].map(x=>x.getAttribute("data-smart-runtime"));'
    + 'const next=current.includes(id)?current.filter(x=>x!==id):current.concat(id);'
    + 'if(!next.length){$("runtime-note").textContent=' + t('至少保留一种来源', 'Keep at least one source') + ';return}commitRuntimes(next)};'
    + 'const RUNTIME_NOTE=' + t('关掉的来源会跳过。至少保留一种。', 'Sources you turn off are skipped. Keep at least one.') + ';'
    + 'for(const b of document.querySelectorAll("[data-smart-runtime]")){const tip=b.getAttribute("data-tip")||"";'
    + 'b.onmouseenter=b.onfocus=()=>{$("runtime-note").textContent=tip};'
    + 'b.onmouseleave=b.onblur=()=>{if($("runtime-note").textContent===tip)$("runtime-note").textContent=RUNTIME_NOTE}};'
    + 'function paintPort(port){const n=Number(port)||0;const fixed=n>0;'
    + '$("port-random").classList.toggle("primary",!fixed);$("port-fixed").classList.toggle("primary",fixed);'
    + '$("port-fixed-block").hidden=!fixed;if(fixed)$("port").value=String(n);else if(!$("port").value)$("port").value=""}'
    + 'async function savePort(value){try{const r=await fetch("desktop/local-web-port",{method:"POST",headers:{"content-type":"application/json"},'
    + 'body:JSON.stringify({localWebPort:value})});const j=await r.json();'
    + 'if(j.saved){paintPort(j.localWebPort);$("port-note").textContent=j.applied?(j.localWebPort?'
    + t('已固定端口，正在重新启动本地服务…', 'Port pinned; restarting the local service…') + ':'
    + t('已改回自动端口，正在重新启动本地服务…', 'Back to automatic port selection; restarting the local service…') + '):'
    + t('已保存', 'Saved') + '}else{$("port-note").textContent=' + t('保存失败：', 'Save failed: ')
    + '+(j.error||' + t('未知错误', 'unknown error') + ');paintPort(j.localWebPort)}}'
    + 'catch(e){$("port-note").textContent=' + t('保存失败：', 'Save failed: ') + '+e.message}}'
    + '$("port-random").onclick=()=>{paintPort(0);void savePort(0)};'
    + '$("port-fixed").onclick=()=>{$("port-random").classList.remove("primary");$("port-fixed").classList.add("primary");'
    + '$("port-fixed-block").hidden=false;$("port").focus()};'
    + '$("port-save").onclick=()=>{const v=$("port").value.trim();if(!v){$("port-note").textContent='
    + t('请输入端口', 'Enter a port') + ';return}void savePort(v)};'
    + 'let dataMode="shared";'
    + 'function paintDataMode(mode,path,reason,plugins,selectable){dataMode=mode==="isolated"?"isolated":"shared";'
    + '$("data-shared").classList.toggle("primary",dataMode==="shared");$("data-isolated").classList.toggle("primary",dataMode==="isolated");'
    + '$("data-shared").setAttribute("aria-checked",String(dataMode==="shared"));$("data-isolated").setAttribute("aria-checked",String(dataMode==="isolated"));'
    + '$("data-shared").disabled=selectable===false;$("data-isolated").disabled=selectable===false;'
    + 'const probe=document.querySelector("[data-smart-runtime=probe]");if(probe)probe.disabled=dataMode==="isolated";'
    + '$("data-path").textContent=path||"";'
    + '$("data-note").textContent=selectable===false?'
    + t('当前由 DSH_HOME 开发环境变量控制。', 'Currently controlled by the DSH_HOME development override.')
    + ':reason==="plugin-compatibility"?'
    + '(' + t('因共享环境中的插件与当前 DSH 不兼容，当前使用独立环境。解决后可切回共享环境。', 'The isolated environment is in use because plugins in the shared environment are incompatible with the current DSH. Switch back after resolving them.')
    + '+(plugins&&plugins.length?' + t(' 问题插件：', ' Problem plugins: ') + '+plugins.join(' + t('、', ', ') + '):""))'
    + ':dataMode==="shared"?'
    + t('与命令行和浏览器版 DSH 共用对话、凭据、模型配置与插件。', 'Shares conversations, credentials, model configuration and plugins with the DSH CLI and browser UI.')
    + ':' + t('使用桌面端独立的数据、凭据与插件。切换会重启客户端。', 'Uses isolated desktop data, credentials and plugins. Switching restarts the client.') + '}'
    + 'async function saveDataMode(mode){if(mode===dataMode)return;const buttons=[$("data-shared"),$("data-isolated")];buttons.forEach(b=>b.disabled=true);'
    + '$("data-note").textContent=' + t('正在保存并重启客户端…', 'Saving and restarting the client…') + ';'
    + 'try{const r=await fetch("desktop/dsh-data-mode",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dshDataMode:mode})});const j=await r.json();'
    + 'if(!j.saved){buttons.forEach(b=>b.disabled=false);$("data-note").textContent=' + t('切换失败：', 'Switch failed: ') + '+(j.error||' + t('未知错误', 'unknown error') + ');return}'
    + 'if(j.applied){$("data-note").textContent=' + t('已保存，正在重启客户端…', 'Saved; restarting the client…') + ';return}'
    + 'await refresh();$("data-note").textContent=' + t('当前已经是这个环境', 'This environment is already selected') + '}'
    + 'catch(e){buttons.forEach(b=>b.disabled=false);$("data-note").textContent=' + t('切换失败：', 'Switch failed: ') + '+e.message}}'
    + '$("data-shared").onclick=()=>void saveDataMode("shared");$("data-isolated").onclick=()=>void saveDataMode("isolated");'
    // Any answer must put the button back; a fetch that throws would otherwise
    // leave it grey until the page is reopened.
    + '$("update-check").onclick=async()=>{try{$("update-check").disabled=true;const r=await fetch("desktop/update/check",{method:"POST"});renderUpdate((await r.json()).state)}'
    + 'catch(e){$("update-check").disabled=false;$("update-status").hidden=false;$("update-status").classList.add("error");$("update-status").textContent=' + t('检查失败：', 'Check failed: ') + '+e.message}};'
    // The install answers only when the download is done, so the page says what
    // it is doing now, and puts the button back for any answer that never began.
    + '$("update-install").onclick=async()=>{const fail=t=>{$("update-install").disabled=false;'
    + '$("update-status").hidden=false;$("update-status").classList.add("error");$("update-status").textContent=' + t('安装失败：', 'Install failed: ') + '+t};'
    + 'try{$("update-install").disabled=true;$("update-status").hidden=false;$("update-status").textContent=' + t('正在准备下载…', 'Preparing the download…') + ';'
    + 'const r=await fetch("desktop/update/install",{method:"POST"});const j=await r.json();if(j.state)renderUpdate(j.state);'
    + 'if(!j.started)fail(j.error||' + t('未知错误', 'unknown error') + ')}catch(e){fail(e.message)}};'
    + '$("update-dismiss").onclick=async()=>{await fetch("desktop/update/dismiss",{method:"POST"});renderUpdate(await(await fetch("desktop/update")).json())};'
    + 'refresh();'
    + 'setInterval(async()=>{try{const u=await(await fetch("desktop/update")).json();if(u.phase==="downloading"||u.phase==="installing")renderUpdate(u)}catch(e){}},400);'
}
