import { releaseNotesCss } from '../release-notes.ts'
import { RELEASES_PAGE_URL } from '../updater.ts'

const EXTERNAL_LINK_SVG = '<svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor"'
  + ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">'
  + '<path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>'
  + '<path d="M15 3h6v6"></path><path d="M10 14 21 3"></path></svg>'

export function renderSettingsPageHtml(chinese: boolean, icon: string): string {
  // Plain text, not escaped: every value below is a literal written here, and
  // none of them contains a character HTML or an attribute would read.
  const h = (zh: string, en: string): string => chinese ? zh : en
  return '<!doctype html><html lang="' + (chinese ? 'zh-CN' : 'en') + '"><head><meta charset="utf-8">'
    + '<title>' + h('DSH Desktop 设置', 'DSH Desktop settings') + '</title>'
    + '<meta http-equiv="Content-Security-Policy" content="default-src \'self\'; img-src data:; style-src \'unsafe-inline\'">'
    + '<meta name="color-scheme" content="light dark">'
    + '<style>:root{color-scheme:light dark}'
    + '*{box-sizing:border-box;margin:0;padding:0}'
    + 'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif;font-size:14px;line-height:1.6;background:#fff;color:#0f1115;min-height:100vh;display:flex;justify-content:center;padding:48px 24px 40px}'
    + '.container{width:100%;max-width:560px}'
    // Header: centered logo + title, matching loading page
    + '.header{text-align:center;margin-bottom:36px}'
    + '.mark{width:56px;height:56px;border-radius:14px;box-shadow:0 12px 32px rgba(15,17,21,.14)}'
    + '.page-title{margin:18px 0 0;font-size:18px;font-weight:600;letter-spacing:-.01em}'
    // Section titles with badge
    + '.section{margin-bottom:24px}'
    + '.section-title{display:flex;align-items:center;gap:8px;margin:0 0 6px;font-size:14px;font-weight:500}'
    + '.section-title .actions{margin-left:auto;margin-top:0}'
    + '.badge{font-size:11px;font-weight:400;background:#EBEEF2;border-radius:999px;padding:2px 8px;color:#6e7480}'
    // Text hierarchy
    + '.status-text{margin:0 0 12px;font-size:13px;color:#6e7480;overflow-wrap:anywhere}'
    + '.version-text{margin:0 0 4px;font-size:12px;color:#9aa0a6}'
    // Input
    + 'input{width:100%;background:#fff;border:1px solid #d8d8d4;border-radius:8px;padding:7px 11px;font-size:13px;font-family:inherit;color:#0f1115;outline:none;transition:border-color .15s ease}'
    + 'input:focus{border-color:#0f1115}'
    + 'input::placeholder{color:#9aa0a6}'
    // Action buttons
    + '.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}'
    + '.runtime-picks{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}'
    + '.custom-row{display:flex;gap:8px;align-items:center;margin-top:12px}'
    + '.custom-row input{flex:1;min-width:0;width:auto;margin:0}'
    + 'button{white-space:nowrap;font-weight:400;background:transparent;border:1px solid #d8d8d4;border-radius:28px;padding:6px 18px;font-size:13px;font-family:inherit;color:#0f1115;cursor:pointer;transition:background .15s ease,opacity .15s ease}'
    + 'button:hover{background:#f5f6f7}'
    + 'button:disabled{cursor:default;opacity:.5}'
    + 'button.primary{background:#0f1115;border-color:#0f1115;color:#fff}'
    + 'button.primary:hover{opacity:.88;background:#0f1115}'
    // The manual-download seat: a glyph rather than a fourth button, so the
    // row keeps one primary action and this stays a way out, not a choice.
    + '.icon-link{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;'
    + 'border-radius:999px;color:#6e7480;text-decoration:none;transition:background .15s ease,color .15s ease}'
    + '.icon-link:hover{background:#f5f6f7;color:#0f1115}'
    + '[hidden]{display:none}'
    + '.note{margin:8px 0 0;font-size:13px;color:#6e7480}'
    + '.path-text{overflow-wrap:anywhere;word-break:break-word}'
    // Divider
    + '.divider{border:none;border-top:1px solid #ebeef2;margin:28px 0}'
    // Download progress
    + '.progress{height:4px;margin:0 0 10px;border-radius:999px;background:#ebeef2;overflow:hidden}'
    + '.progress span{display:block;height:100%;width:0;border-radius:999px;background:#0f1115;transition:width .2s ease}'
    + '.status-text.error{color:#d93f3f}'
    // Update notes: release Markdown, rendered in the main process. The
    // stylesheet is shared with the card injected into the Web UI settings.
    + releaseNotesCss('#update-notes', { text: '#6e7480', strong: '#0f1115', border: '#d8d8d4', surface: '#ebeef2' })
    // Dark mode
    + '@media(prefers-color-scheme:dark){body{background:#17181a;color:#f4f5f6}'
    + '.mark{box-shadow:0 12px 32px rgba(0,0,0,.34)}'
    + '.badge{background:#2c2e33;color:#818791}'
    + '.status-text{color:#aeb3bb}.version-text{color:#818791}'
    + 'input{background:#1e1f22;border-color:#3a3d42;color:#f4f5f6}'
    + 'input:focus{border-color:#f4f5f6}input::placeholder{color:#5a5e66}'
    + 'button{border-color:#3a3d42;color:#f4f5f6}button:hover{background:#232529}'
    + 'button.primary{background:#f4f5f6;border-color:#f4f5f6;color:#17181a}'
    + 'button.primary:hover{opacity:.88;background:#f4f5f6}'
    + '.icon-link{color:#aeb3bb}.icon-link:hover{background:#232529;color:#f4f5f6}'
    + '.note{color:#aeb3bb}.divider{border-color:#2c2e33}'
    + '.progress{background:#2c2e33}.progress span{background:#f4f5f6}'
    + '.status-text.error{color:#ff6b6b}'
    + releaseNotesCss('#update-notes', { text: '#aeb3bb', strong: '#f4f5f6', border: '#3a3d42', surface: '#232529' })
    + '}'
    // Reduced motion
    + '@media(prefers-reduced-motion:reduce){*{transition:none!important}}'
    + '</style></head><body><div class="container">'
    // Header with logo
    + '<div class="header">' + icon + '<h1 class="page-title">' + h('DSH Desktop 设置', 'DSH Desktop settings') + '</h1></div>'
    // Connection section
    + '<div class="section">'
    + '<div class="section-title">' + h('连接', 'Connection') + '<span class="badge">' + h('增强功能', 'Enhanced') + '</span></div>'
    + '<p class="status-text" id="status">' + h('连接状态读取中…', 'Reading connection status…') + '</p>'
    + '<div class="runtime-picks" role="radiogroup" aria-label="' + h('连接方式', 'Connection mode') + '">'
    + '<button type="button" id="mode-smart" class="primary">' + h('智能', 'Smart') + '</button>'
    + '<button type="button" id="mode-custom">' + h('自定义', 'Custom') + '</button>'
    + '</div>'
    + '<div id="smart-block">'
    + '<p class="note" style="margin-top:14px">' + h('可多选，按优先级依次尝试', 'Pick any; tried in this order') + '</p>'
    + '<div class="runtime-picks">'
    + '<button type="button" data-smart-runtime="probe" class="primary" data-tip="' + h('本机已有官方 Web UI 在跑时直接连上（默认 3080），不另起一份。', 'Connect to an official Web UI already running on this machine (3080 by default) instead of starting another.') + '" aria-description="' + h('本机已有官方 Web UI 在跑时直接连上（默认 3080），不另起一份。', 'Connect to an official Web UI already running on this machine (3080 by default) instead of starting another.') + '">' + h('本机已运行', 'Already running') + '</button>'
    + '<button type="button" data-smart-runtime="installed" class="primary" data-tip="' + h('用你 PATH 上自己安装的 dsh，由客户端在后台启动。', 'Start the dsh on your own PATH, in the background, from this client.') + '" aria-description="' + h('用你 PATH 上自己安装的 dsh，由客户端在后台启动。', 'Start the dsh on your own PATH, in the background, from this client.') + '">' + h('本机已安装', 'Installed') + '</button>'
    + '<button type="button" data-smart-runtime="npx" class="primary" data-tip="' + h('用你跑过 npx @deepseek-ai/dsh 留下的缓存包启动，不联网。', 'Start from the package that npx @deepseek-ai/dsh left in your cache. No network.') + '" aria-description="' + h('用你跑过 npx @deepseek-ai/dsh 留下的缓存包启动，不联网。', 'Start from the package that npx @deepseek-ai/dsh left in your cache. No network.') + '">' + h('npx 缓存', 'npx cache') + '</button>'
    + '<button type="button" data-smart-runtime="bundled" class="primary" data-tip="' + h('用安装包自带的官方运行时，不用另装 Node 或 dsh。', 'Use the official runtime shipped inside this client. No separate Node or dsh needed.') + '" aria-description="' + h('用安装包自带的官方运行时，不用另装 Node 或 dsh。', 'Use the official runtime shipped inside this client. No separate Node or dsh needed.') + '">' + h('客户端内置', 'Bundled') + '</button>'
    + '</div>'
    + '<p class="note" id="runtime-note">' + h('关掉的来源会跳过。至少保留一种。', 'Sources you turn off are skipped. Keep at least one.') + '</p>'
    + '<p class="note" style="margin-top:14px">' + h('本地服务端口', 'Local service port') + '</p>'
    + '<div class="runtime-picks" role="radiogroup" aria-label="' + h('本地服务端口', 'Local service port') + '">'
    + '<button type="button" id="port-random" class="primary">' + h('自动', 'Automatic') + '</button>'
    + '<button type="button" id="port-fixed">' + h('固定', 'Fixed') + '</button>'
    + '</div>'
    + '<div id="port-fixed-block" hidden>'
    + '<div class="custom-row">'
    + '<input id="port" inputmode="numeric" placeholder="' + h('例如 13080', 'e.g. 13080') + '" spellcheck="false">'
    + '<button id="port-save">' + h('保存', 'Save') + '</button>'
    + '</div>'
    + '</div>'
    + '<p class="note" id="port-note">' + h('仅影响客户端自己启动的 dsh。自动依次尝试 3080、13080，均被占用时使用随机端口；固定端口不自动回退。', 'Only a dsh this client starts. Automatic mode tries 3080, then 13080, then an OS-assigned port. A pinned port does not fall back.') + '</p>'
    + '</div>'
    + '<div id="custom-block" hidden>'
    + '<div class="custom-row">'
    + '<input id="url" placeholder="' + h('例如 http://127.0.0.1:3080', 'e.g. http://127.0.0.1:3080') + '" spellcheck="false">'
    + '<button id="save">' + h('保存并连接', 'Save and connect') + '</button>'
    + '</div>'
    + '<p class="note">' + h('直连该地址上的 Web UI。服务停掉后不会自动改用本地运行时。', 'Connects straight to the Web UI at that address. If it stops, this client does not fall back to a local runtime.') + '</p>'
    + '</div>'
    + '<p class="note" id="note"></p>'
    + '</div>'
    // Divider
    + '<hr class="divider">'
    // DSH data environment section
    + '<div class="section">'
    + '<div class="section-title">' + h('数据环境', 'Data environment') + '<span class="badge">DSH_HOME</span></div>'
    + '<div class="runtime-picks data-mode-picks" role="radiogroup" aria-label="' + h('DSH 数据环境', 'DSH data environment') + '">'
    + '<button type="button" role="radio" aria-checked="true" id="data-shared" class="primary">' + h('共享环境', 'Shared') + '</button>'
    + '<button type="button" role="radio" aria-checked="false" id="data-isolated">' + h('桌面端独立环境', 'Desktop isolated') + '</button>'
    + '</div>'
    + '<p class="version-text path-text" id="data-path"></p>'
    + '<p class="note" id="data-note" aria-live="polite">' + h('正在读取数据环境…', 'Reading data environment…') + '</p>'
    + '</div>'
    + '<hr class="divider">'
    // The native settings window remains complete when official DOM integration is unavailable.
    + '<div class="section"><div class="section-title"><span id="market-label">' + h('安全市场', 'Safe marketplace') + '</span>'
    + '<div class="actions"><button id="market-toggle" type="button" role="switch" aria-checked="false" aria-labelledby="market-label" disabled>'
    + h('正在读取…', 'Loading…') + '</button></div></div>'
    + '<p class="status-text" id="market-note" aria-live="polite"></p></div><hr class="divider">'
    // Update section
    + '<div class="section">'
    + '<div class="section-title">' + h('应用更新', 'App updates') + '<span class="badge">' + h('增强功能', 'Enhanced') + '</span>'
    + '<div class="actions">'
    + '<a class="icon-link" id="update-page" href="' + RELEASES_PAGE_URL + '" target="_blank" rel="noreferrer"'
    + ' title="' + h('打开 GitHub 发布页手动下载', 'Open the GitHub releases page to download manually') + '" aria-label="' + h('打开 GitHub 发布页手动下载', 'Open the GitHub releases page to download manually') + '">' + EXTERNAL_LINK_SVG + '</a>'
    + '<button id="update-install" class="primary" hidden>' + h('下载并安装', 'Download and install') + '</button>'
    + '<button id="update-check">' + h('检查更新', 'Check for updates') + '</button>'
    + '<button id="update-dismiss" hidden>' + h('稍后提醒', 'Remind me later') + '</button>'
    + '</div></div>'
    + '<p class="version-text" id="versions"></p>'
    + '<p class="status-text" id="update-status" hidden></p>'
    + '<div class="progress" id="update-bar" hidden><span></span></div>'
    + '<div id="update-notes" hidden></div>'
    + '</div>'
    + '</div><script src="desktop/settings.js"></script></body></html>'
}
