/** Owns packaged command paths, generated shims and the inherited shell environment. */
import { app } from 'electron'
import { spawn } from 'node:child_process'
import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { userInfo } from 'node:os'
import { delimiter, isAbsolute, join } from 'node:path'
import { devFlag } from './development-options.ts'
import { isSameDirectory, normalizePathEntry } from './runtime-resolution.ts'
import { PNPM_ENTRY_VARIABLE } from './runtime-spawn.ts'
import type { DshCommand } from './runtime-types.ts'
const SPAWN_NO_WINDOW = { windowsHide: true } as const

export function createRuntimeEnvironment(options: { appDir: string; clientHome(): string; childHome(): string }) {
  const { appDir: APP_DIR, clientHome, childHome } = options

  /**
   * A packaged client bundles a complete dsh runtime but no `node` / `dsh` /
   * `pnpm` commands, so a user who never installed those tools gets an Agent
   * that cannot run `node script.js`, `dsh plugin …`, or any MCP server started
   * that way. Publish them in the client's data home and append that directory
   * to the runtime's PATH: appended, never prepended, so a real tool the user
   * installed keeps priority and a developer's toolchain is unaffected.
   *
   * `dsh` goes through `dsh-cli.mjs` (fail-closed: it will not boot a second
   * profile on this DSH_HOME). `pnpm` goes through `runtime-launcher.mjs`
   * instead, so lifecycle-script children do not inherit `ELECTRON_RUN_AS_NODE`.
   * `DSH_HOME` is filled in only when missing: the child already inherits it,
   * and an Agent that set `DSH_HOME=x dsh …` must keep that value.
   *
   * The shims are written once per launch — the executable path moves with each
   * installed version, so they are rewritten rather than reused across versions —
   * and only exist in packaged builds, where the developer Node that runs the
   * child would otherwise already be on PATH. The result is memoized because the
   * runtime is respawned on every bounded restart, and neither the files nor
   * their log lines should be repeated per attempt.
   * Returns the directory to append, or undefined when there is nothing to add.
   */
  let shimDirMemo: string | undefined

  let shimsResolved = false


  /**
   * The Node that runs the dsh child. Inside a packaged app the child runs on
   * Electron's own bundled Node (ELECTRON_RUN_AS_NODE), so the end user needs
   * neither a system Node nor any npm command; in development the system Node
   * (or DSH_DESKTOP_NODE) is used.
   */
  function nodeForChild(): string {
    if (app.isPackaged) return process.execPath
    return process.env.DSH_DESKTOP_NODE ?? 'node'
  }


  /**
   * The small module the runtime child boots instead of the official bin: it
   * keeps `ELECTRON_RUN_AS_NODE` out of the Agent's execution environment while
   * the runtime's own `process.execPath` children keep it (see
   * `src/main/runtime-launcher.ts`). It ships beside the runtime closure rather
   * than inside app.asar, because the child reads it as an ordinary file.
   */
  function runtimeLauncher(): string {
    return app.isPackaged
      ? join(process.resourcesPath, 'runtime-launcher.mjs')
      : join(APP_DIR, '.build', 'runtime-launcher.mjs')
  }


  /** Packaged `pnpm.mjs` the launcher rewrites `dsh plugin`'s `pnpm` spawns onto. */
  function bundledPnpmEntry(): string | undefined {
    const entry = app.isPackaged
      ? join(process.resourcesPath, 'dsh-runtime', 'node_modules', 'pnpm', 'bin', 'pnpm.mjs')
      : join(APP_DIR, 'dsh-runtime', 'node_modules', 'pnpm', 'bin', 'pnpm.mjs')
    return existsSync(entry) ? entry : undefined
  }


  function ensureShims(): string | undefined {
    if (shimsResolved) return shimDirMemo
    shimsResolved = true
    if (!app.isPackaged) return undefined
    try {
      const binDir = join(clientHome(), 'bin')
      mkdirSync(binDir, { recursive: true })
      writeNodeShim(binDir)
      writeDshShim(binDir)
      writePnpmShim(binDir)
      shimDirMemo = binDir
      console.log('[desktop] runtime shims ready: ' + binDir)
      return binDir
    } catch (error) {
      // A missing shim costs the Agent one convenience, never the session.
      console.warn('[desktop] runtime shims unavailable: ' + (error instanceof Error ? error.message : String(error)))
      return undefined
    }
  }


  function writeNodeShim(binDir: string): void {
    if (process.platform === 'win32') {
      writeFileSync(join(binDir, 'node.cmd'), [
        '@echo off',
        'rem Generated by DSH Desktop. Electron\'s bundled Node, named `node`.',
        'setlocal',
        'set "ELECTRON_RUN_AS_NODE=1"',
        '"' + process.execPath + '" %*',
        'exit /b %ERRORLEVEL%',
        '',
      ].join('\r\n'))
      return
    }
    const shim = join(binDir, 'node')
    writeFileSync(shim, [
      '#!/bin/sh',
      '# Generated by DSH Desktop. Electron\'s bundled Node, named `node`.',
      'ELECTRON_RUN_AS_NODE=1 exec "' + process.execPath + '" "$@"',
      '',
    ].join('\n'))
    chmodSync(shim, 0o755)
  }


  function writeDshShim(binDir: string): void {
    const bundled = resolveBundledDsh()
    if (bundled === undefined) return
    const cli = join(process.resourcesPath, 'dsh-cli.mjs')
    if (!existsSync(cli)) return
    const home = childHome()
    const entry = bundled.binPath
    const pnpm = bundledPnpmEntry()
    if (process.platform === 'win32') {
      writeFileSync(join(binDir, 'dsh.cmd'), [
        '@echo off',
        'rem Generated by DSH Desktop. The bundled dsh CLI, named `dsh`.',
        'setlocal',
        'if not defined DSH_HOME set "DSH_HOME=' + home + '"',
        'set "ELECTRON_RUN_AS_NODE=1"',
        'set "DSH_DESKTOP_RUNTIME_ENTRY=' + entry + '"',
        ...pnpm === undefined ? [] : ['set "' + PNPM_ENTRY_VARIABLE + '=' + pnpm + '"'],
        '"' + process.execPath + '" --expose-internals "' + cli + '" %*',
        'exit /b %ERRORLEVEL%',
        '',
      ].join('\r\n'))
      return
    }
    const shim = join(binDir, 'dsh')
    writeFileSync(shim, [
      '#!/bin/sh',
      '# Generated by DSH Desktop. The bundled dsh CLI, named `dsh`.',
      '[ -n "$DSH_HOME" ] || DSH_HOME="' + home + '"',
      'export DSH_HOME',
      ...pnpm === undefined ? [] : [PNPM_ENTRY_VARIABLE + '="' + pnpm + '" \\'],
      'DSH_DESKTOP_RUNTIME_ENTRY="' + entry + '" ELECTRON_RUN_AS_NODE=1 \\',
      '  exec "' + process.execPath + '" --expose-internals "' + cli + '" "$@"',
      '',
    ].join('\n'))
    chmodSync(shim, 0o755)
  }


  function writePnpmShim(binDir: string): void {
    const entry = bundledPnpmEntry()
    if (entry === undefined) return
    const launcher = runtimeLauncher()
    if (process.platform === 'win32') {
      writeFileSync(join(binDir, 'pnpm.cmd'), [
        '@echo off',
        'rem Generated by DSH Desktop. The bundled pnpm CLI, named `pnpm`.',
        'setlocal',
        'set "ELECTRON_RUN_AS_NODE=1"',
        'set "DSH_DESKTOP_RUNTIME_ENTRY=' + entry + '"',
        'set "' + PNPM_ENTRY_VARIABLE + '=' + entry + '"',
        '"' + process.execPath + '" "' + launcher + '" %*',
        'exit /b %ERRORLEVEL%',
        '',
      ].join('\r\n'))
      return
    }
    const shim = join(binDir, 'pnpm')
    writeFileSync(shim, [
      '#!/bin/sh',
      '# Generated by DSH Desktop. The bundled pnpm CLI, named `pnpm`.',
      PNPM_ENTRY_VARIABLE + '="' + entry + '" \\',
      'DSH_DESKTOP_RUNTIME_ENTRY="' + entry + '" ELECTRON_RUN_AS_NODE=1 \\',
      '  exec "' + process.execPath + '" "' + launcher + '" "$@"',
      '',
    ].join('\n'))
    chmodSync(shim, 0o755)
  }


  /** The PATH the runtime child (and every Agent command under it) inherits. */
  function childPath(): string {
    const current = process.env.PATH ?? ''
    const shimDir = ensureShims()
    if (shimDir === undefined) return current
    // Same directory comparison as findOnPath's exclusion: an entry already on
    // PATH under another spelling is already the shim directory.
    if (current.split(delimiter)
      .some(entry => isSameDirectory(normalizePathEntry(entry), shimDir, process.platform))) return current
    return current === '' ? shimDir : current + delimiter + shimDir
  }


  /**
   * macOS GUI applications inherit launchd's small PATH instead of the user's
   * login-shell PATH. The official runtime later derives Agent command
   * environments from this process, so Homebrew and version-manager tools would
   * otherwise disappear only in the packaged app. Read one PATH value through
   * the user's absolute login shell, with a short deadline and no interactive
   * startup, then merge only absolute path entries into the existing value.
   */
  /**
   * Read one PATH value out of the user's shell. NUL framing survives the
   * banners, colour codes, and version-manager chatter an interactive startup
   * file prints; only the last framed pair is read back.
   */
  async function readShellPath(shellPath: string, shellArgs: string[], timeoutMs: number): Promise<string | undefined> {
    return new Promise<string | undefined>((resolve) => {
      let settled = false
      let stdout = ''
      const finish = (value?: string): void => {
        if (settled) return
        settled = true
        clearTimeout(timeout)
        resolve(value)
      }
      const child = spawn(shellPath, [...shellArgs, 'printf \'\\0%s\\0\' "$PATH"'], {
        env: process.env,
        stdio: ['ignore', 'pipe', 'ignore'],
        ...SPAWN_NO_WINDOW,
      })
      const timeout = setTimeout(() => {
        child.kill()
        finish()
      }, timeoutMs)
      child.stdout.on('data', (chunk: Buffer) => {
        stdout += chunk.toString()
        if (stdout.length > 65_536) stdout = stdout.slice(-65_536)
      })
      child.once('error', () => { finish() })
      child.once('exit', (code) => {
        const end = stdout.lastIndexOf('\0')
        const start = end > 0 ? stdout.lastIndexOf('\0', end - 1) : -1
        finish(code === 0 && start >= 0 && end > start ? stdout.slice(start + 1, end) : undefined)
      })
    })
  }


  async function restoreMacGuiPath(): Promise<void> {
    if (process.platform !== 'darwin' || !app.isPackaged || devFlag('DSH_DESKTOP_SKIP_LOGIN_PATH')) return

    const configuredShell = userInfo().shell
    const shellPath = typeof configuredShell === 'string' && isAbsolute(configuredShell) && existsSync(configuredShell)
      ? configuredShell
      : '/bin/zsh'
    // Interactive first: a login shell alone reads .zprofile but never .zshrc,
    // where most people's tool directories (~/.local/bin, language-manager shims)
    // actually live — those tools exist in the user's terminal and would
    // otherwise be missing only inside the desktop client. An interactive
    // startup can be slow or, with an unusual rc file, not terminate at all, so
    // it runs against a deadline and falls back to the plain login shell.
    const loginPath = await readShellPath(shellPath, ['-l', '-i', '-c'], 3_000)
      ?? await readShellPath(shellPath, ['-l', '-c'], 2_000)

    // Shells that model PATH as a list (fish) join it with spaces rather than the
    // path delimiter, which yields one long pseudo-absolute entry. Requiring the
    // directory to exist drops that value instead of prepending a bogus entry.
    const fromLogin = (loginPath ?? '').split(delimiter)
      .map(entry => entry.trim())
      .filter(entry => entry !== '' && isAbsolute(entry) && existsSync(entry))
    const fromLaunch = (process.env.PATH ?? '').split(delimiter)
      .map(entry => entry.trim())
      .filter(entry => entry !== '' && isAbsolute(entry))
    const merged = [...new Set([...fromLogin, ...fromLaunch])].join(delimiter)
    if (merged === '') {
      console.warn('[desktop] login-shell PATH unavailable; keeping the launch environment')
      return
    }
    process.env.PATH = merged
    console.log('[desktop] restored PATH from the macOS login shell')
  }


  /**
   * The bundled dsh CLI. Release builds use pnpm deploy to materialize the
   * complete production closure outside app.asar; development resolves the same
   * pinned package from the dsh-runtime workspace. An end user needs neither a
   * system Node nor a separately installed dsh command.
   */
  function resolveBundledDsh(): DshCommand | undefined {
    try {
      const bin = app.isPackaged
        ? join(process.resourcesPath, 'dsh-runtime', 'node_modules', '@deepseek-ai', 'dsh', 'lib', 'bin.js')
        : createRequire(join(APP_DIR, 'dsh-runtime', 'package.json')).resolve('@deepseek-ai/dsh/lib/bin.js')
      if (!existsSync(bin)) return undefined
      return {
        command: nodeForChild(),
        // System Node can use node-addon-require-builtin, but Electron's Node
        // mode does not expose the loader required by cordis-plugin-hmr through
        // that addon and exits with "--expose-internals is required". Keep the
        // unstable flag scoped to the packaged child; source audit and package
        // smoke intentionally cover both execution paths.
        args: [...app.isPackaged ? ['--expose-internals'] : [], runtimeLauncher()],
        entry: bin,
        binPath: bin,
        label: bin,
        source: 'bundled',
      }
    } catch {
      return undefined
    }
  }
  return { nodeForChild, runtimeLauncher, bundledPnpmEntry, childPath, restoreMacGuiPath, resolveBundledDsh }
}
export type RuntimeEnvironment = ReturnType<typeof createRuntimeEnvironment>
